"""lance

Revision ID: a380847f38c9
Revises: 
Create Date: 2024-01-03 09:26:01.174658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a380847f38c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eletronico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voltagem', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leilao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_futura', sa.DateTime(timezone=80), nullable=False),
    sa.Column('data_visitacao', sa.DateTime(timezone=80), nullable=False),
    sa.Column('detalhes', sa.String(length=120), nullable=False),
    sa.Column('qtd_produtos', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('EM ABERTO', 'EM ANDAMENTO', 'FINALIZADO', name='status_enum'), server_default='EM ABERTO', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('ano', sa.String(length=4), nullable=False),
    sa.Column('qtd_portas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('lance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('leilao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['leilao_id'], ['leilao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lance')
    op.drop_table('veiculos')
    op.drop_table('leilao')
    op.drop_table('eletronico')
    op.drop_table('cliente')
    # ### end Alembic commands ###
