"""Migracao do veiculo e eletronico

Revision ID: c1555d4d9fd7
Revises: 7ca1fef35fa6
Create Date: 2024-01-02 15:17:01.559664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1555d4d9fd7'
down_revision = '7ca1fef35fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eletronico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voltagem', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('ano', sa.String(length=4), nullable=False),
    sa.Column('qtd_portas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo')
    op.drop_table('eletronico')
    # ### end Alembic commands ###
